# Generated by Django 2.0.5 on 2020-07-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, verbose_name='课程名称')),
                ('classes', models.CharField(default='', max_length=50, verbose_name='班级')),
                ('description', models.TextField(verbose_name='课程描述')),
                ('student', models.ManyToManyField(blank=True, to='project.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='project.Teacher')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
    ]
