# Generated by Django 2.0.5 on 2020-07-12 06:25

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='正文')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('file', models.FileField(blank=True, upload_to=project.models.user_directory_path, verbose_name='文件')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('published', models.DateTimeField(null=True, verbose_name='发布时间')),
                ('status', models.CharField(choices=[('d', '草稿'), ('p', '发表')], default='p', max_length=1, verbose_name='作业状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='project.Course')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'ordering': ['-modified'],
            },
        ),
    ]
