# Generated by Django 2.0.5 on 2020-07-12 06:28

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='正文')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('file', models.FileField(blank=True, upload_to=project.models.user_directory_path, verbose_name='文件')),
                ('score', models.IntegerField(null=True, verbose_name='分数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handin', to='project.Student')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handin', to='project.Course')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handin', to='project.Homework')),
            ],
            options={
                'verbose_name': '作答',
                'verbose_name_plural': '作答',
            },
        ),
    ]
